"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
import dj_database_url
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Get the debug status from environment variables
# The 'False' string is the default if the variable isn't found
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# My backend url
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

ALLOWED_HOSTS = ['localhost']

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'corsheaders',
    'rest_framework',
    'debug_toolbar',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'api.middleware.DebugUserMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



ASGI_APPLICATION = 'backend.asgi.application'

REDIS_URL = os.environ.get('REDIS_CHANNEL_URL')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                # Use a single entry with the secure rediss:// protocol
                "hosts": [(REDIS_URL)],
            },
        },
    }
else:
    # Fallback for local development if the environment variable is not set
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [('127.0.0.1', 6379)],
            },
        },
    }






WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if the DATABASE_URL environment variable exists
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        # Get database configuration from a DATABASE_URL environment variable
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
# For local development, you can set a fallback if the env var isn't present
else:
    DATABASES = {
        'default':{
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'hippocampus',
            'USER': 'ray',
            'PASSWORD': 'uppercut_ray',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 100,
                'retry_on_timeout': True,
            },
            # 'SENTINEL_KWARGS': {
            #     'socket_timeout': 0.1,
            # },
            # Add this for secure connections (TLS/SSL), which is standard for cloud databases.
            # "SSL_CERT_REQS": None,
        }
    }
}

INTERNAL_IPS = [
    '127.0.0.1',
]


# Configure the Debug Toolbar
DEBUG_TOOLBAR_PANELS =  [
    'debug_toolbar.panels.cache.CachePanel',
    # other panels
]

Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'task_broker'
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Add this setting to tell Django how to authenticate users
AUTHENTICATION_BACKENDS = [
    'api.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend', # Keep the default backend for admin login
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- Static Files Settings (for Whitenoise) ---
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# being handled in STORAGES now
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# AWS
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")

# File storage
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")

AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

STORAGES = {
    # For media files (FileField, ImageField)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "audio_storage/",          # All media files will be in <bucket>/audio_storage/
            "file_overwrite": False,      # Don't overwrite files with the same name
        },
    },
    # For static files (CSS, JS, images for your app)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Add this at the end of the file
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
]

# Additionally, for Django 4.0+ you should also configure CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
]

# Add this line to specify your custom user model
AUTH_USER_MODEL = 'api.User'

# This tells Django it's okay to accept cookies from those origins.
CORS_ALLOW_CREDENTIALS = True

# You might also need to explicitly state which headers are allowed.
# This tells the browser that Content-Type and the CSRF token header are okay.
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# This ensures the session cookie can be sent cross-site.
# Modern browsers require SameSite='None' to be paired with Secure=True.
# This works fine on localhost for modern browsers.
if not DEBUG: # production
    SESSION_COOKIE_SAMESITE = 'None' # None for development / 'None' in Deployment
    CSRF_COOKIE_SAMESITE = 'None'  # Lax for development
else:
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = not DEBUG  # false in development
SESSION_COOKIE_SECURE = not DEBUG  # false in development 
# When you go to production (HTTPS), you should set these back to True.

# Add these new lines:
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'sessionid'
SESSION_SAVE_EVERY_REQUEST = True

# Add this entire block
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # This is the key. It enables session-based authentication, which
        # is what you are using. It correctly handles CSRF for POST/PUT/DELETE
        # requests while allowing safe GET requests.
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # This sets a sensible default: all API endpoints require the
        # user to be authenticated unless specified otherwise.
        'rest_framework.permissions.IsAuthenticated',
    ]
}




# Celery Configuration Options
BROKER_URL = os.environ.get('RABBITMQ')
if BROKER_URL:
    CELERY_BROKER_URL = BROKER_URL
else:
    CELERY_BROKER_URL = 'amqp://127.0.0.1:5672'


CACHE_BACKEND_URL = os.environ.get('REDIS')
if CACHE_BACKEND_URL:
    CELERY_RESULT_BACKEND = CACHE_BACKEND_URL
else:
    CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
