# Generated by Django 5.2.7 on 2025-11-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cognee_nodeset_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
